In [1]:
import numpy as np
A = np.random.rand(500, 500)


In [2]:
A

array([[ 0.38947302,  0.94956717,  0.50574888, ...,  0.36285587,
         0.09752955,  0.9855612 ],
       [ 0.6228641 ,  0.56375389,  0.20093244, ...,  0.92204157,
         0.45295179,  0.22543472],
       [ 0.80364699,  0.99255816,  0.2221022 , ...,  0.03256109,
         0.70264494,  0.98356349],
       ..., 
       [ 0.04218516,  0.35413354,  0.31865952, ...,  0.5473069 ,
         0.00277001,  0.56504525],
       [ 0.14342147,  0.93907218,  0.82503274, ...,  0.02501733,
         0.34552155,  0.25858366],
       [ 0.87293486,  0.54183107,  0.52489948, ...,  0.5650952 ,
         0.55463096,  0.77089467]])

In [12]:
A = [[2, 2, 1, 2, 2],[1, 1, 1, 1, 1],[2, 2, 1, 2, 2],[2, 1,2,1, 2],[2, 1, 2, 1, 2]]
A

[[2, 2, 1, 2, 2],
 [1, 1, 1, 1, 1],
 [2, 2, 1, 2, 2],
 [2, 1, 2, 1, 2],
 [2, 1, 2, 1, 2]]

In [13]:
timeit A[A>1.5] = 5
A

SyntaxError: invalid syntax (<ipython-input-13-e5dc733d3cd1>, line 1)

In [14]:
A = np.matrix(A)


In [15]:
timeit A[A>1.5] = 5

The slowest run took 5.14 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 22.6 µs per loop


In [16]:
A

matrix([[5, 5, 1, 5, 5],
        [1, 1, 1, 1, 1],
        [5, 5, 1, 5, 5],
        [5, 1, 5, 1, 5],
        [5, 1, 5, 1, 5]])

In [17]:
A = np.zeros((640,1080))
A 


array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [18]:
timeit A[A<0.5] = 5


The slowest run took 5.82 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.44 ms per loop


In [19]:
B = np.minimum(A)

ValueError: invalid number of arguments

In [20]:
B = np.min(A)

In [21]:
B

5.0